import type { FindingSeverity, SopAnalyticsFinding } from "@/types/sop-analytics";

export type SopSignals = {
  valid: boolean; processOwner: boolean; trigger: boolean; approval: boolean; escalation: boolean;
  exceptions: boolean; successCriteria: boolean; kpis: boolean; compliance: boolean; retention: boolean;
  checklist: boolean; training: boolean; unsupportedAssumptions: boolean; grounded: boolean;
  procedureCount: number; vagueStepCount: number;
};

type Rule = { when: (s: SopSignals) => boolean; id: string; severity: FindingSeverity; title: string; description: string; section: string; recommendation: string; action: string };
const rules: Rule[] = [
  { when:s=>!s.valid,id:"invalid-sop",severity:"critical",title:"SOP data is invalid",description:"The record cannot be analyzed as a valid ProcessForge SOP.",section:"Document",recommendation:"Restore a valid version or regenerate the SOP.",action:"Review and rebuild this SOP using the current structured format." },
  { when:s=>!s.processOwner,id:"missing-owner",severity:"high",title:"Missing process owner",description:"Accountability for maintaining and governing the process is unclear.",section:"Roles",recommendation:"Assign a named role as process owner.",action:"Add a process owner with governance, review and exception responsibilities." },
  { when:s=>!s.trigger,id:"missing-trigger",severity:"high",title:"Missing trigger",description:"The event that starts the process is not explicit.",section:"Procedure",recommendation:"Define a measurable starting condition.",action:"Add a clear process trigger and required starting inputs." },
  { when:s=>!s.approval,id:"missing-approval",severity:"high",title:"Missing approval control",description:"No approval decision, authority or evidence is defined.",section:"Controls",recommendation:"Add approval roles, thresholds and recorded evidence.",action:"Add a measurable approval workflow with owner, authority and evidence." },
  { when:s=>!s.escalation,id:"missing-escalation",severity:"high",title:"Missing escalation path",description:"Staff lack a defined route when work cannot proceed normally.",section:"Escalation rules",recommendation:"Define escalation conditions, recipient and response timing.",action:"Add an escalation path with triggers, owners and response times." },
  { when:s=>!s.exceptions,id:"missing-exceptions",severity:"medium",title:"Missing exception handling",description:"Non-standard cases and failure paths are not addressed.",section:"Procedure",recommendation:"Describe exceptions, decision rights and recovery steps.",action:"Add exception handling and recovery steps for likely failure scenarios." },
  { when:s=>!s.successCriteria,id:"missing-success",severity:"high",title:"Missing measurable success criteria",description:"Completion cannot be objectively verified.",section:"Controls",recommendation:"Add measurable completion and acceptance criteria.",action:"Add measurable success criteria and completion evidence." },
  { when:s=>!s.kpis,id:"missing-kpis",severity:"medium",title:"No KPIs",description:"The SOP does not define performance indicators.",section:"Controls",recommendation:"Add a small set of measurable operational KPIs.",action:"Add practical KPIs with target, owner, measurement method and review frequency." },
  { when:s=>s.vagueStepCount>0,id:"vague-steps",severity:"medium",title:"Vague procedure steps",description:"One or more steps lack sufficient action, ownership or evidence detail.",section:"Procedure",recommendation:"Rewrite vague steps with observable actions and outputs.",action:"Strengthen vague procedure steps with direct actions, owners, timing and evidence." },
  { when:s=>!s.compliance,id:"missing-compliance",severity:"low",title:"No compliance guidance",description:"Applicable policy or regulatory checks are not identified.",section:"Compliance",recommendation:"Identify applicable requirements or explicitly state that review is required.",action:"Add compliance-control placeholders without inventing laws, policies or certifications." },
  { when:s=>!s.retention,id:"missing-retention",severity:"medium",title:"No record-retention rule",description:"Required records lack an owner, location or retention period.",section:"Records",recommendation:"Define record location, access and retention requirements.",action:"Add a records section with evidence owner, storage location and retention rule placeholders." },
  { when:s=>!s.checklist,id:"missing-checklist",severity:"medium",title:"No quality checklist",description:"Operators have no concise completion-control checklist.",section:"Quality checklist",recommendation:"Add verifiable quality-control checks.",action:"Add a quality checklist with measurable pass/fail checks." },
  { when:s=>!s.training,id:"missing-training",severity:"medium",title:"No training validation",description:"The SOP does not validate operator understanding.",section:"Training quiz",recommendation:"Add scenario-based questions and valid answers.",action:"Improve the training quiz with scenario-based questions and unambiguous answers." },
  { when:s=>s.unsupportedAssumptions,id:"unsupported-assumptions",severity:"high",title:"Unsupported company-specific assumptions",description:"Company-specific assumptions are present without supporting knowledge sources.",section:"Source Notes",recommendation:"Validate assumptions against an approved company source.",action:"Clearly label unsupported company-specific assumptions and request owner validation." },
  { when:s=>!s.grounded,id:"weak-grounding",severity:"improvement",title:"Weak knowledge grounding",description:"No company reference document supports this SOP.",section:"Knowledge sources",recommendation:"Ground the SOP in approved company documents when available.",action:"Identify the company documents needed to validate this SOP." },
  { when:s=>s.procedureCount<4,id:"short-procedure",severity:"medium",title:"Procedure is excessively short",description:"The procedure may omit operational handoffs or controls.",section:"Procedure",recommendation:"Add the missing operational sequence, decisions and evidence.",action:"Expand the procedure into a complete measurable sequence without adding unsupported policy." },
];

export function detectSopRisks(signals: SopSignals): SopAnalyticsFinding[] {
  return rules.filter(rule=>rule.when(signals)).map(rule=>({id:rule.id,severity:rule.severity,title:rule.title,description:rule.description,affectedSection:rule.section,recommendation:rule.recommendation,suggestedEditorAction:rule.action,resolved:false}));
}
