import { createClient } from "@/lib/supabase/client";
import { authenticatedClient } from "@/lib/cloud/auth";
import { cloudFailure,type CloudResult } from "@/lib/cloud/result";
import { sopSchema,migrateSopSnapshot,type Sop } from "@/lib/sop-schema";
import { sopToInsert } from "@/lib/cloud/mappers";
import type { MarketplaceTemplate } from "@/types/marketplace";
import type { Database } from "@/types/database";
type Row=Database["public"]["Tables"]["sop_templates"]["Row"];
type PublicRow=Database["public"]["Views"]["public_marketplace_templates"]["Row"];

export async function fetchMarketplaceTemplates(options:{mine?:boolean}={}):Promise<CloudResult<MarketplaceTemplate[]>>{
 try{const db=createClient();if(options.mine){const{data:{user}}=await db.auth.getUser();if(!user)return cloudFailure("Sign in to manage templates.","auth");const{data,error}=await db.from("sop_templates").select("*").eq("creator_id",user.id).order("published_at",{ascending:false});if(error)return cloudFailure("Templates could not be loaded.");return{ok:true,data:await hydrate(db,data??[])}}const{data,error}=await db.from("public_marketplace_templates").select("*").order("published_at",{ascending:false});if(error)return cloudFailure("Templates could not be loaded.");return{ok:true,data:await hydrate(db,data??[])}}catch{return cloudFailure("Marketplace is unavailable.")}
}
export async function fetchMarketplaceTemplate(slug:string):Promise<CloudResult<MarketplaceTemplate>>{try{const db=createClient();const{data,error}=await db.from("public_marketplace_templates").select("*").eq("slug",slug).single();if(error||!data)return cloudFailure("Template could not be found.");const values=await hydrate(db,[data]);return values[0]?{ok:true,data:values[0]}:cloudFailure("Template data is invalid.","validation")}catch{return cloudFailure("Marketplace is unavailable.")}}
async function hydrate(db:ReturnType<typeof createClient>,rows:Array<Row|PublicRow>):Promise<MarketplaceTemplate[]>{if(!rows.length)return[];const ids=rows.map(x=>x.id),creatorIds=[...new Set(rows.map(x=>x.creator_id))],categoryIds=[...new Set(rows.map(x=>x.category_id).filter(Boolean))] as string[];const[tags,categories,creators]=await Promise.all([db.from("template_tags").select("*").in("template_id",ids),categoryIds.length?db.from("template_categories").select("*").in("id",categoryIds):Promise.resolve({data:[]}),db.from("marketplace_creator_profiles").select("*").in("user_id",creatorIds)]);return rows.flatMap(row=>{const parsed=sopSchema.safeParse(migrateSopSnapshot(row.template_content));if(!parsed.success)return[];return[{id:row.id,creatorId:row.creator_id,sourceSopId:"source_sop_id" in row?row.source_sop_id:null,title:row.title,slug:row.slug,summary:row.summary,description:row.description,industry:row.industry,department:row.department,categoryId:row.category_id,categoryName:categories.data?.find(x=>x.id===row.category_id)?.name??"Uncategorized",tags:(tags.data??[]).filter(x=>x.template_id===row.id).map(x=>x.tag),sop:parsed.data,previewContent:row.preview_content,visibility:row.visibility,publicationStatus:row.publication_status,moderationStatus:row.moderation_status,version:row.version,complianceFramework:row.compliance_framework,riskLevel:row.risk_level,isFree:row.is_free,paidReady:row.paid_ready,usageCount:row.usage_count,favoriteCount:row.favorite_count,ratingAverage:Number(row.rating_average),ratingCount:row.rating_count,createdAt:row.created_at,updatedAt:row.updated_at,publishedAt:row.published_at,creatorName:creators.data?.find(x=>x.user_id===row.creator_id)?.display_name??"ProcessForge Creator"}]})}
export async function copyTemplateToWorkspace(template:MarketplaceTemplate,workspaceId:string):Promise<CloudResult<string>>{const auth=await authenticatedClient();if(!auth.ok)return auth;const copy:Sop={...template.sop,documentId:`PF-TPL-${crypto.randomUUID().slice(0,8).toUpperCase()}`,version:"1.0",title:template.title};const insert={...sopToInsert(copy,auth.data.userId,workspaceId,{industry:template.industry??undefined,department:template.department??undefined}),source_template_id:template.id};const{data,error}=await auth.data.client.from("sops").insert(insert as never).select("id").single();if(error||!data)return cloudFailure("Template could not be copied to this workspace.");await auth.data.client.from("template_usage").insert({template_id:template.id,user_id:auth.data.userId,event_type:"copy"});return{ok:true,data:data.id}}
export async function rateTemplate(id:string,rating:number):Promise<CloudResult<true>>{const auth=await authenticatedClient();if(!auth.ok)return auth;if(!Number.isInteger(rating)||rating<1||rating>5)return cloudFailure("Choose a rating from 1 to 5.","validation");const{error}=await auth.data.client.from("template_ratings").upsert({template_id:id,user_id:auth.data.userId,rating},{onConflict:"template_id,user_id"});return error?cloudFailure("Rating could not be saved."):{ok:true,data:true}}
export async function toggleTemplateFavorite(id:string,favorite:boolean):Promise<CloudResult<true>>{const auth=await authenticatedClient();if(!auth.ok)return auth;const query=favorite?auth.data.client.from("template_favorites").insert({template_id:id,user_id:auth.data.userId}):auth.data.client.from("template_favorites").delete().eq("template_id",id).eq("user_id",auth.data.userId);const{error}=await query;return error?cloudFailure("Favorite could not be updated."):{ok:true,data:true}}
export async function trackTemplateView(id:string){try{const key=`processforge.template-view.${id}`;if(sessionStorage.getItem(key))return;sessionStorage.setItem(key,"1");await createClient().from("template_usage").insert({template_id:id,event_type:"view",session_key:crypto.randomUUID()})}catch{/* Metrics never block browsing. */}}
export async function updateOwnTemplate(id:string,update:{title?:string;summary?:string;description?:string;publication_status?:string;moderation_status?:string;version?:string;published_at?:string|null}):Promise<CloudResult<true>>{const auth=await authenticatedClient();if(!auth.ok)return auth;const{error}=await auth.data.client.from("sop_templates").update(update).eq("id",id).eq("creator_id",auth.data.userId);return error?cloudFailure("Template could not be updated."):{ok:true,data:true}}
