import { z } from "zod";
import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { createInvitationToken } from "@/lib/invitations/token";
import { sendInvitationEmail } from "@/lib/invitations/resend";
export const runtime="nodejs";
const schema=z.discriminatedUnion("action",[z.object({action:z.literal("create"),workspaceId:z.uuid(),email:z.email().max(320),role:z.enum(["admin","editor","viewer"])}),z.object({action:z.literal("resend"),invitationId:z.uuid()}),z.object({action:z.literal("revoke"),invitationId:z.uuid()})]);

export async function POST(request:Request){
  let input:z.infer<typeof schema>;try{input=schema.parse(await request.json())}catch{return response("Invalid invitation request.",400)}
  let supabase;try{supabase=await createClient()}catch{return response("Invitation service is unavailable.",503)}
  const{data:{user},error:userError}=await supabase.auth.getUser();if(userError||!user)return response("Please sign in to manage invitations.",401);
  let workspaceId:string;
  if(input.action==="create")workspaceId=input.workspaceId;else{const{data,error}=await supabase.from("workspace_invitations").select("workspace_id").eq("id",input.invitationId).maybeSingle();if(error||!data){logDiagnostic({userId:user.id,invitationId:input.invitationId,workspaceId:null,membership:null,role:null,helperRole:null,allowed:false,action:input.action,errorCode:error?.code,errorMessage:error?.message});return response("Invitation or workspace could not be found.",404)}workspaceId=data.workspace_id}
  const[memberResult,roleResult]=await Promise.all([supabase.from("workspace_members").select("workspace_id,user_id,role").eq("workspace_id",workspaceId).eq("user_id",user.id).maybeSingle(),supabase.rpc("workspace_role_for",{target:workspaceId})]);
  if(memberResult.error){logDiagnostic({userId:user.id,invitationId:input.action==="create"?null:input.invitationId,workspaceId,membership:null,role:null,helperRole:roleResult.data??null,allowed:false,action:input.action,errorCode:memberResult.error.code,errorMessage:memberResult.error.message});return response("Workspace permission could not be verified. Please retry.",500)}
  const membership=memberResult.data;const detectedRole=membership?.role??null;const allowed=detectedRole==="owner"||detectedRole==="admin";
  logDiagnostic({userId:user.id,invitationId:input.action==="create"?null:input.invitationId,workspaceId,membership,role:detectedRole,helperRole:roleResult.data??null,allowed,action:input.action,errorCode:roleResult.error?.code,errorMessage:roleResult.error?.message});
  if(!allowed)return response("Only workspace owners and admins can manage invitations.",403);
  if(input.action==="revoke"){const{data,error}=await supabase.from("workspace_invitations").update({status:"revoked",token_hash:null}).eq("id",input.invitationId).eq("status","pending").select("id").maybeSingle();if(error){logRpcError("revoke",error);return rpcError(error)}return!data?response("Invitation is no longer pending.",409):NextResponse.json({ok:true})}
  const token=createInvitationToken();let invitationId:string;
  if(input.action==="create"){const{data,error}=await supabase.rpc("create_workspace_email_invitation",{target_workspace:workspaceId,target_email:input.email,target_role:input.role,target_token_hash:token.hash});if(error||!data){if(error)logRpcError("create",error);return rpcError(error)}invitationId=data}else{const{data,error}=await supabase.rpc("prepare_workspace_invitation_resend",{target_invitation:input.invitationId,target_token_hash:token.hash});if(error||!data){if(error)logRpcError("resend",error);return rpcError(error)}invitationId=data}
  logDiagnostic({userId:user.id,invitationId,workspaceId,membership,role:detectedRole,helperRole:roleResult.data??null,allowed:true,action:input.action,errorCode:roleResult.error?.code,errorMessage:roleResult.error?.message});
  const{data:invitation,error:inviteError}=await supabase.from("workspace_invitations").select("*").eq("id",invitationId).single();if(inviteError||!invitation)return response("Invitation created but email delivery failed.",500,{invitationCreated:true});
  const[{data:workspace},{data:profile}]=await Promise.all([supabase.from("workspaces").select("name").eq("id",invitation.workspace_id).single(),supabase.from("profiles").select("display_name").eq("id",user.id).maybeSingle()]);
  const baseUrl=getAppUrl();if(!baseUrl){await markDelivery(supabase,invitationId,false,"Application URL is not configured.");return response("Invitation created but email delivery failed.",502,{invitationCreated:true})}
  const acceptUrl=`${baseUrl}/invitations/accept?token=${encodeURIComponent(token.token)}`;const sent=await sendInvitationEmail({to:invitation.email,workspaceName:workspace?.name??"a ProcessForge workspace",inviterName:profile?.display_name||user.email||"A ProcessForge teammate",role:invitation.role,expiresAt:invitation.expires_at,acceptUrl,idempotencyKey:`workspace-invite-${invitationId}-${token.hash.slice(0,12)}`});
  await markDelivery(supabase,invitationId,sent.ok,sent.ok?null:sent.message);return sent.ok?NextResponse.json({ok:true,invitationId,emailStatus:"sent"}):response("Invitation created but email delivery failed.",502,{invitationCreated:true,invitationId,emailStatus:"failed"});
}
function getAppUrl(){const value=process.env.NEXT_PUBLIC_APP_URL?.trim().replace(/\/$/,"");if(!value)return null;try{const url=new URL(value);return url.protocol==="https:"||url.hostname==="localhost"&&url.protocol==="http:"?url.origin:null}catch{return null}}
async function markDelivery(supabase:Awaited<ReturnType<typeof createClient>>,id:string,sent:boolean,error:string|null){await supabase.from("workspace_invitations").update({email_delivery_status:sent?"sent":"failed",email_delivery_error:error?.slice(0,500)??null,sent_at:new Date().toISOString()}).eq("id",id)}
type SupabaseError={code?:string;message?:string};
function rpcError(error?:SupabaseError|null){const message=error?.message??"",code=error?.code??"";if(code==="PGRST202"||code==="42883")return response("The latest invitation database migration has not been applied.",503);if(message.includes("RATE_LIMITED"))return response("Please wait before resending this invitation.",429);if(message.includes("ALREADY_PENDING"))return response("An invitation is already pending for this email.",409);if(message.includes("ALREADY_MEMBER"))return response("This person is already a workspace member.",409);if(message.includes("SELF"))return response("You cannot invite yourself.",400);if(message.includes("INVALID_EMAIL"))return response("Enter a valid email address.",400);if(message.includes("INVALID_ROLE"))return response("Choose Admin, Editor, or Viewer.",400);if(message.includes("WORKSPACE_NOT_FOUND")||message.includes("NOT_FOUND"))return response("This workspace or invitation no longer exists.",404);if(message.includes("ALREADY_ACCEPTED"))return response("This invitation was already accepted.",409);if(message.includes("REVOKED"))return response("This invitation was revoked.",410);if(message.includes("INSUFFICIENT_PERMISSIONS")||code==="42501")return response("Only workspace owners and admins can manage invitations.",403);return response("Invitation operation failed. Please retry.",500)}
function logDiagnostic(value:{userId:string;invitationId:string|null;workspaceId:string|null;membership:{workspace_id:string;user_id:string;role:string}|null;role:string|null;helperRole:string|null;allowed:boolean;action:string;errorCode?:string;errorMessage?:string}){if(process.env.NODE_ENV!=="production")console.info("[ProcessForge invitation permission]",value)}
function logRpcError(action:string,error:SupabaseError){if(process.env.NODE_ENV!=="production")console.error("[ProcessForge invitation RPC]",{action,code:error.code,message:error.message})}
function response(error:string,status:number,extra:Record<string,unknown>={}){return NextResponse.json({error,...extra},{status})}
