import Link from "next/link";

export default function AgentDocsPage() {
  return <main className="min-h-screen bg-background px-4 py-16 text-foreground"><article className="mx-auto max-w-3xl space-y-8">
    <div><p className="text-xs font-semibold uppercase tracking-[.18em] text-emerald-500">ProcessForge AI agent API</p><h1 className="mt-2 text-3xl font-semibold">Official x402 SOP generation</h1><p className="mt-3 text-muted-foreground">The paid endpoint uses the official OKX x402 middleware and exact payments on X Layer. Check metadata and health for current payment availability.</p></div>
    <section><h2 className="text-lg font-medium">Payment flow</h2><p className="mt-2 text-sm text-muted-foreground">A valid unpaid request receives an official HTTP 402 challenge. An official buyer signs the returned requirement without changing it. The middleware verifies and settles the payment before the payment-independent SOP handler executes.</p></section>
    <section><h2 className="text-lg font-medium">Request</h2><pre className="mt-2 overflow-x-auto rounded-lg bg-muted p-4 text-xs">{`POST /api/agent/generate-sop\nIdempotency-Key: pf-unique-request-001\nContent-Type: application/json\n\n${JSON.stringify({ title: "Supplier invoice approval", description: "Validate each invoice, obtain approval, record evidence, and schedule payment.", industry: "Finance", department: "Accounting", audience: "Accounts payable team", requirements: ["Record approval evidence"], compliance_frameworks: [], output_format: "json" }, null, 2)}`}</pre></section>
    <section><h2 className="text-lg font-medium">Successful response</h2><p className="mt-2 text-sm text-muted-foreground">HTTP 200 JSON contains <code>request_id</code>, <code>service</code>, <code>status</code>, <code>sop</code>, <code>analytics</code>, <code>compliance</code>, <code>assumptions</code>, <code>warnings</code>, <code>generated_at</code>, <code>processing_time_ms</code>, and <code>schema_version</code>.</p></section>
    <section><h2 className="text-lg font-medium">Errors</h2><p className="mt-2 text-sm text-muted-foreground"><code>400 INVALID_REQUEST</code>; <code>402 PAYMENT_REQUIRED</code>; <code>405 METHOD_NOT_ALLOWED</code>; <code>409 IDEMPOTENCY_CONFLICT</code>; <code>429 RATE_LIMITED</code>; <code>503 SERVICE_BUSY/PAYMENT_CONFIGURATION_ERROR</code>.</p></section>
    <section><h2 className="text-lg font-medium">Security</h2><p className="mt-2 text-sm text-muted-foreground">Never send facilitator credentials or private keys to this API. Raw proofs are not persisted; replay protection stores a one-way evidence fingerprint.</p></section>
    <section><h2 className="text-lg font-medium">Free endpoints</h2><p className="mt-2 text-sm text-muted-foreground"><code>GET /api/agent</code> provides metadata; <code>GET /api/agent/health</code> provides redacted readiness.</p></section>
    <Link href="/" className="text-sm text-emerald-400 hover:underline">Return to ProcessForge</Link>
  </article></main>;
}
