"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { AlertTriangle, BarChart3, CheckCircle2, RefreshCw, Search } from "lucide-react";
import { WorkspaceHeader } from "@/components/processforge/workspace-header";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { analyzeSop } from "@/lib/analytics/sop-analytics";
import { compareSopAnalytics } from "@/lib/analytics/version-comparison";
import { fetchSops, type CloudSop } from "@/lib/cloud/sop-service";
import { fetchVersions } from "@/lib/cloud/version-service";
import { fetchWorkspaces, type Workspace } from "@/lib/cloud/workspace-service";

type Item=CloudSop&{score:number;risk:string;improvement:number};
export function AnalyticsDashboard(){
 const[items,setItems]=useState<Item[]>([]),[workspaces,setWorkspaces]=useState<Workspace[]>([]);const[loading,setLoading]=useState(true),[error,setError]=useState("");const[q,setQ]=useState(""),[workspace,setWorkspace]=useState(""),[industry,setIndustry]=useState(""),[department,setDepartment]=useState(""),[status,setStatus]=useState(""),[risk,setRisk]=useState(""),[sort,setSort]=useState("score-desc");
 const load=useCallback(async()=>{setLoading(true);setError("");const[sops,spaces,versions]=await Promise.all([fetchSops({allWorkspaces:true}),fetchWorkspaces(),fetchVersions()]);if(!sops.ok){setError(sops.error.message);setLoading(false);return}if(spaces.ok)setWorkspaces(spaces.data);setItems(sops.data.map(item=>{const analytics=analyzeSop(item.sop);const snapshots=versions.ok?versions.data.filter(v=>v.sopId===item.row.id).sort((a,b)=>Date.parse(b.timestamp)-Date.parse(a.timestamp)):[];const improvement=snapshots.length>1?compareSopAnalytics(snapshots[1].sop,snapshots[0].sop).scoreDelta:0;return{...item,score:analytics.overallQuality,risk:analytics.riskLevel,improvement}}));setLoading(false)},[]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
 const industries=[...new Set(items.map(x=>x.row.industry).filter(Boolean))] as string[],departments=[...new Set(items.map(x=>x.row.department).filter(Boolean))] as string[];
 const visible=useMemo(()=>items.filter(x=>(!q||`${x.row.title} ${x.sop.documentId}`.toLowerCase().includes(q.toLowerCase()))&&(!workspace||x.row.workspace_id===workspace)&&(!industry||x.row.industry===industry)&&(!department||x.row.department===department)&&(!status||x.row.status===status)&&(!risk||x.risk===risk)).sort((a,b)=>sort==="score-asc"?a.score-b.score:sort==="title"?a.row.title.localeCompare(b.row.title):sort==="improved"?b.improvement-a.improvement:b.score-a.score),[items,q,workspace,industry,department,status,risk,sort]);
 const average=items.length?Math.round(items.reduce((n,x)=>n+x.score,0)/items.length):0,high=items.filter(x=>x.risk==="high"||x.risk==="critical").length,review=items.filter(x=>x.score<75||x.risk==="high"||x.risk==="critical").length,ready=items.filter(x=>x.score>=80&&x.risk==="low").length,grounded=items.filter(x=>x.sop.knowledgeSources.documentNames.length>0).length;
 return <main className="min-h-screen bg-background"><WorkspaceHeader/><div className="mx-auto max-w-7xl space-y-6 px-4 py-8 sm:px-6"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-emerald-500">Quality intelligence</p><h1 className="mt-2 text-2xl font-semibold">SOP Analytics</h1><p className="mt-2 text-sm text-muted-foreground">Deterministic quality, readiness and operational-risk insights across your workspaces.</p></div>
 <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6">{[["Average quality",average],["SOPs analyzed",items.length],["High risk",high],["Needs review",review],["Operationally ready",ready],["Knowledge grounded",grounded]].map(([label,value])=><div key={String(label)} className="rounded-xl border border-border bg-card/50 p-4"><p className="text-2xl font-semibold">{value}{label==="Average quality"?"%":""}</p><p className="text-xs text-muted-foreground">{label}</p></div>)}</div>
 <div className="grid gap-4 lg:grid-cols-2"><Distribution title="Quality distribution" values={[["Excellent (85–100)",items.filter(x=>x.score>=85).length],["Ready (70–84)",items.filter(x=>x.score>=70&&x.score<85).length],["Basic (50–69)",items.filter(x=>x.score>=50&&x.score<70).length],["Needs detail (0–49)",items.filter(x=>x.score<50).length]]}/><Distribution title="Risk distribution" values={[["Critical",items.filter(x=>x.risk==="critical").length],["High",items.filter(x=>x.risk==="high").length],["Medium",items.filter(x=>x.risk==="medium").length],["Low",items.filter(x=>x.risk==="low").length]]}/></div>
 <div className="grid gap-4 lg:grid-cols-3"><Ranking title="Top-performing SOPs" items={[...items].sort((a,b)=>b.score-a.score).slice(0,3)}/><Ranking title="Lowest-scoring SOPs" items={[...items].sort((a,b)=>a.score-b.score).slice(0,3)}/><Ranking title="Recently improved SOPs" items={[...items].filter(x=>x.improvement>0).sort((a,b)=>b.improvement-a.improvement).slice(0,3)} showImprovement/></div>
 <section className="overflow-hidden rounded-xl border border-border bg-card/30"><div className="grid gap-2 border-b border-border p-4 md:grid-cols-4 lg:grid-cols-7"><div className="relative md:col-span-2"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input className="pl-9" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search SOPs" aria-label="Search analytics"/></div><Filter label="Workspace" value={workspace} set={setWorkspace} options={workspaces.map(x=>[x.id,x.name])}/><Filter label="Industry" value={industry} set={setIndustry} options={industries.map(x=>[x,x])}/><Filter label="Department" value={department} set={setDepartment} options={departments.map(x=>[x,x])}/><Filter label="Status" value={status} set={setStatus} options={[["draft","Draft"],["in_review","In Review"],["approved","Approved"],["archived","Archived"]]}/><Filter label="Risk" value={risk} set={setRisk} options={[["critical","Critical"],["high","High"],["medium","Medium"],["low","Low"]]}/></div><div className="flex justify-end border-b border-border px-4 py-2"><Filter label="Sort" value={sort} set={setSort} includeAll={false} options={[["score-desc","Highest score"],["score-asc","Lowest score"],["improved","Recently improved"],["title","Title"]]}/></div>
 {loading?<div className="space-y-3 p-6">{[1,2,3].map(x=><div key={x} className="h-16 animate-pulse rounded-lg bg-white/5"/>)}</div>:error?<div className="p-12 text-center"><p role="alert" className="text-sm text-rose-300">{error}</p><Button variant="outline" className="mt-4" onClick={()=>void load()}><RefreshCw/>Retry</Button></div>:visible.length===0?<div className="p-16 text-center"><BarChart3 className="mx-auto size-7 text-muted-foreground"/><p className="mt-3 text-sm text-muted-foreground">No SOP analytics match these filters.</p></div>:<div className="divide-y divide-border">{visible.map(x=><Link key={x.row.id} href={`/create?cloud=${x.row.id}`} className="grid gap-3 p-4 transition hover:bg-white/[.03] sm:grid-cols-[1fr_auto_auto] sm:items-center"><div><p className="text-sm font-medium">{x.row.title}</p><p className="mt-1 text-[11px] text-muted-foreground">{x.sop.documentId} · {x.row.industry||"No industry"} · {x.row.department||"No department"}</p></div><span className={`inline-flex items-center gap-1 text-xs ${x.risk==="high"||x.risk==="critical"?"text-rose-300":"text-amber-200"}`}>{x.risk==="low"?<CheckCircle2 className="size-3.5"/>:<AlertTriangle className="size-3.5"/>}{x.risk} risk</span><div className="text-right"><p className="text-lg font-semibold text-emerald-400">{x.score}%</p>{x.improvement!==0&&<p className="text-[10px] text-muted-foreground">{x.improvement>0?"+":""}{x.improvement} vs prior version</p>}</div></Link>)}</div>}</section></div></main>
}
function Filter({label,value,set,options,includeAll=true}:{label:string;value:string;set:(v:string)=>void;options:string[][];includeAll?:boolean}){return <select aria-label={label} className="h-9 rounded-md border border-input bg-background px-2 text-xs" value={value} onChange={e=>set(e.target.value)}>{includeAll&&<option value="">All {label.toLowerCase()}s</option>}{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>}
function Distribution({title,values}:{title:string;values:Array<[string,number]>}){const total=Math.max(1,values.reduce((n,x)=>n+x[1],0));return <section className="rounded-xl border border-border bg-card/40 p-4"><h2 className="text-sm font-medium">{title}</h2><div className="mt-4 space-y-3">{values.map(([label,value])=><div key={label}><div className="flex justify-between text-[11px]"><span>{label}</span><span>{value}</span></div><div className="mt-1 h-1.5 rounded-full bg-secondary"><div className="h-full rounded-full bg-emerald-500" style={{width:`${value/total*100}%`}}/></div></div>)}</div></section>}
function Ranking({title,items,showImprovement=false}:{title:string;items:Item[];showImprovement?:boolean}){return <section className="rounded-xl border border-border bg-card/40 p-4"><h2 className="text-sm font-medium">{title}</h2>{items.length?<ol className="mt-3 space-y-2">{items.map(item=><li key={item.row.id}><Link href={`/create?cloud=${item.row.id}`} className="flex items-center justify-between gap-3 rounded-lg border border-border/70 px-3 py-2 text-xs hover:bg-white/[.03]"><span className="truncate">{item.row.title}</span><span className="shrink-0 font-mono text-emerald-400">{showImprovement?`+${item.improvement}`:`${item.score}%`}</span></Link></li>)}</ol>:<p className="mt-4 text-xs text-muted-foreground">No matching SOPs yet.</p>}</section>}
