"use client";
import { useCallback,useEffect,useMemo,useState } from "react";
import Link from "next/link";import { useRouter } from "next/navigation";
import { AlertTriangle,CalendarClock,Download,FileCheck2,RefreshCw,ShieldCheck,Sparkles } from "lucide-react";
import { WorkspaceHeader } from "@/components/processforge/workspace-header";import { Button } from "@/components/ui/button";
import { fetchSops,type CloudSop,scheduleSopReview,saveSopCompliance } from "@/lib/cloud/sop-service";import { fetchVersions,type CloudVersion } from "@/lib/cloud/version-service";
import { analyzeCompliance } from "@/lib/compliance/compliance-engine";import { queueComplianceAiFix } from "@/lib/compliance/ai-fix";import { exportAuditPdf } from "@/lib/compliance/export-audit-pdf";import { exportAuditDocx } from "@/lib/compliance/export-audit-docx";import type { SopCompliance } from "@/types/sop-compliance";
type Item=CloudSop&{compliance:SopCompliance;trend:number};
export function ComplianceDashboard(){const router=useRouter();const[items,setItems]=useState<Item[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[busy,setBusy]=useState<string|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError("");const[sops,versions]=await Promise.all([fetchSops({allWorkspaces:true}),fetchVersions()]);if(!sops.ok){setError(sops.error.message);setLoading(false);return}const all=versions.ok?versions.data:[];setItems(sops.data.map(item=>build(item,all)));setLoading(false)},[]);useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
 const average=items.length?Math.round(items.reduce((n,x)=>n+x.compliance.complianceScore,0)/items.length):0,findings=items.reduce((n,x)=>n+x.compliance.findings.length,0),needs=items.filter(x=>x.compliance.auditStatus!=="ready").length,high=items.filter(x=>["high","critical"].includes(x.compliance.riskRating)).length,trend=items.length?Math.round(items.reduce((n,x)=>n+x.trend,0)/items.length):0;const upcoming=useMemo(()=>items.filter(x=>x.row.next_review_at).sort((a,b)=>Date.parse(a.row.next_review_at!)-Date.parse(b.row.next_review_at!)),[items]);
 const schedule=async(item:Item,days:30|90|180|365)=>{setBusy(item.row.id);const result=await scheduleSopReview(item.row.id,days);if(result.ok){const next=analyzeCompliance(item.sop,{versionCount:2,nextReviewAt:result.data,lastReviewedAt:new Date().toISOString(),reviewIntervalDays:days});await saveSopCompliance(item.row.id,next)}setBusy(null);await load()};const fix=(item:Item,prompt:string)=>{queueComplianceAiFix(prompt);router.push(`/create?cloud=${item.row.id}`)};
 return <main className="min-h-screen bg-background"><WorkspaceHeader/><div className="mx-auto max-w-7xl space-y-6 px-4 py-8 sm:px-6"><header><p className="text-xs font-semibold uppercase tracking-[.18em] text-emerald-500">Enterprise assurance</p><h1 className="mt-2 text-2xl font-semibold">Compliance & Audit Center</h1><p className="mt-2 text-sm text-muted-foreground">Deterministic governance checks, audit reporting and controlled review schedules.</p></header><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[["Overall compliance",`${average}%`,ShieldCheck],["Open findings",findings,AlertTriangle],["SOPs needing review",needs,FileCheck2],["High-risk SOPs",high,AlertTriangle],["Compliance trend",`${trend>=0?"+":""}${trend}`,RefreshCw]].map(([label,value,Icon])=>{const C=Icon as typeof ShieldCheck;return <div key={String(label)} className="rounded-xl border border-border bg-card/50 p-4"><C className="size-4 text-emerald-400"/><p className="mt-3 text-2xl font-semibold">{String(value)}</p><p className="text-xs text-muted-foreground">{String(label)}</p></div>})}</div>
 <section className="rounded-xl border border-border bg-card/40 p-4"><h2 className="flex items-center gap-2 text-sm font-medium"><CalendarClock className="size-4 text-emerald-400"/>Review schedule</h2>{upcoming.length?<div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{upcoming.slice(0,6).map(x=><Link key={x.row.id} href={`/create?cloud=${x.row.id}`} className="rounded-lg border border-border p-3 text-xs"><p className="truncate font-medium">{x.row.title}</p><p className="mt-1 text-muted-foreground">Due {new Date(x.row.next_review_at!).toLocaleDateString()}</p></Link>)}</div>:<p className="mt-3 text-xs text-muted-foreground">No reviews scheduled. Choose a review interval on an SOP below.</p>}</section>
 {loading?<div className="space-y-3">{[1,2,3].map(x=><div key={x} className="h-24 animate-pulse rounded-xl bg-white/5"/>)}</div>:error?<div className="rounded-xl border border-border p-12 text-center"><p role="alert" className="text-rose-300">{error}</p><Button className="mt-4" onClick={()=>void load()}><RefreshCw/>Retry</Button></div>:items.length===0?<div className="rounded-xl border border-border p-16 text-center text-sm text-muted-foreground">No SOPs are available for compliance analysis.</div>:<div className="space-y-4">{items.map(item=><article key={item.row.id} className="rounded-xl border border-border bg-card/40 p-4 sm:p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><Link href={`/create?cloud=${item.row.id}`} className="text-sm font-medium hover:text-emerald-400">{item.row.title}</Link><p className="mt-1 text-[11px] text-muted-foreground">{item.sop.documentId} · {item.compliance.auditStatus.replace("_"," ")} · {item.compliance.riskRating} risk</p></div><div className="flex gap-2"><Button variant="outline" size="sm" onClick={()=>exportAuditPdf(item.sop,item.compliance)}><Download/>PDF</Button><Button variant="outline" size="sm" onClick={()=>void exportAuditDocx(item.sop,item.compliance)}><Download/>DOCX</Button></div></div><div className="mt-4 grid gap-2 sm:grid-cols-4">{[["Compliance",item.compliance.complianceScore],["Audit readiness",item.compliance.auditReadiness],["Documentation",item.compliance.documentationQuality],["Governance",item.compliance.governanceScore]].map(([label,value])=><div key={String(label)} className="rounded-lg border border-border p-3"><p className="text-lg font-semibold text-emerald-400">{value}%</p><p className="text-[10px] text-muted-foreground">{label}</p></div>)}</div><div className="mt-4 flex flex-wrap items-center gap-2"><span className="text-[11px] text-muted-foreground">Schedule review:</span>{([30,90,180,365] as const).map(days=><Button key={days} size="xs" variant="outline" disabled={busy===item.row.id} onClick={()=>void schedule(item,days)}>{days} days</Button>)}</div>{item.compliance.findings.length>0&&<div className="mt-4 space-y-2">{item.compliance.findings.slice(0,3).map(f=><div key={f.id} className="flex flex-col gap-2 rounded-lg border border-border p-3 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><p className="text-xs font-medium">{f.title} <span className="ml-1 text-[9px] uppercase text-amber-300">{f.severity}</span></p><p className="mt-1 text-[11px] text-muted-foreground">{f.recommendation}</p></div><Button size="xs" variant="outline" onClick={()=>fix(item,f.aiFixAction)}><Sparkles/>AI Fix</Button></div>)}</div>}</article>)}</div>}</div></main>}
function build(item:CloudSop,versions:CloudVersion[]):Item{const list=versions.filter(v=>v.sopId===item.row.id).sort((a,b)=>Date.parse(b.timestamp)-Date.parse(a.timestamp));const context={versionCount:list.length,nextReviewAt:item.row.next_review_at,lastReviewedAt:item.row.last_reviewed_at,reviewIntervalDays:item.row.next_review_at?90 as const:null};const compliance=analyzeCompliance(item.sop,context);const trend=list.length>1?compliance.complianceScore-analyzeCompliance(list.at(-1)!.sop,{versionCount:1}).complianceScore:0;return{...item,compliance,trend}}
