"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Archive, Clock3, FileText, Heart, RefreshCw, Search, Trash2 } from "lucide-react";
import { Button, buttonVariants } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { deleteCloudSop, fetchSops, setSopFlags, type CloudSop } from "@/lib/cloud/sop-service";
import { getSopHistory, type SopHistoryEntry } from "@/lib/sop-history";

export function HistoryList(){const [cloud,setCloud]=useState<CloudSop[]>([]);const [local,setLocal]=useState<SopHistoryEntry[]>([]);const [query,setQuery]=useState("");const [error,setError]=useState("");const [loading,setLoading]=useState(true);
 const load=useCallback(async()=>{setLoading(true);setError("");const r=await fetchSops();if(r.ok)setCloud(r.data);else{setError(`${r.error.message} Showing this browser's local history.`);setLocal(getSopHistory())}setLoading(false)},[]);useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
 const q=query.trim().toLowerCase();const items=useMemo(()=>cloud.filter(x=>!q||[x.row.title,x.row.industry,x.row.department,x.sop.documentId].some(v=>v?.toLowerCase().includes(q))),[cloud,q]);const locals=local.filter(x=>!q||[x.title,x.industry,x.department,x.documentId].some(v=>v.toLowerCase().includes(q)));
 async function flags(item:CloudSop,next:{is_favorite?:boolean;is_archived?:boolean}){const r=await setSopFlags(item.row.id,next);if(r.ok)setCloud(v=>v.map(x=>x.row.id===item.row.id?{...x,row:{...x.row,...next}}:x));else setError(r.error.message)}
 async function remove(item:CloudSop){if(!confirm(`Permanently delete “${item.row.title}” and all its versions?`))return;const r=await deleteCloudSop(item.row.id);if(r.ok)setCloud(v=>v.filter(x=>x.row.id!==item.row.id));else setError(r.error.message)}
 return <section><div className="flex gap-3 border-b border-border/80 pb-5"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input className="pl-9" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search title, industry, department or document ID"/></div><Button variant="outline" onClick={()=>void load()}><RefreshCw/>Retry</Button></div>{error&&<p className="mt-4 rounded-lg bg-amber-400/10 p-3 text-sm text-amber-200">{error}</p>}{loading?<div className="space-y-3 py-6">{[1,2,3].map(x=><div key={x} className="h-16 animate-pulse rounded-lg bg-white/5"/>)}</div>:items.length? <div className="divide-y divide-border">{items.map(item=><article key={item.row.id} className="flex flex-col gap-4 py-5 sm:flex-row sm:items-center"><HistoryInfo title={item.row.title} documentId={item.sop.documentId} industry={item.row.industry??"Unspecified"} department={item.row.department??"Unspecified"} date={item.row.updated_at}/><div className="flex gap-1"><Link className={buttonVariants({variant:"outline",size:"sm"})} href={`/create?cloud=${item.row.id}`}>{item.row.is_archived?"Restore":"Open"}</Link><Button variant="ghost" size="icon-sm" aria-label="Favorite" onClick={()=>void flags(item,{is_favorite:!item.row.is_favorite})}><Heart className={item.row.is_favorite?"fill-rose-400 text-rose-400":""}/></Button><Button variant="ghost" size="icon-sm" aria-label={item.row.is_archived?"Restore":"Archive"} onClick={()=>void flags(item,{is_archived:!item.row.is_archived})}><Archive/></Button><Button variant="ghost" size="icon-sm" aria-label="Delete" onClick={()=>void remove(item)}><Trash2/></Button></div></article>)}</div>:locals.length?<div className="divide-y divide-border">{locals.map(item=><article key={item.id} className="flex items-center gap-4 py-5"><HistoryInfo title={item.title} documentId={item.documentId} industry={item.industry} department={item.department} date={item.generatedAt}/><Link className={buttonVariants({variant:"outline",size:"sm"})} href={`/create?history=${item.id}`}>Open local</Link></article>)}</div>:<div className="py-24 text-center"><FileText className="mx-auto size-8 text-muted-foreground"/><h2 className="mt-4 font-medium">No SOPs yet</h2><p className="mt-1 text-sm text-muted-foreground">Generated SOPs will be saved locally and synced to your account.</p><Link href="/create" className={buttonVariants({className:"mt-5"})}>Create an SOP</Link></div>}</section>}
function HistoryInfo({title,documentId,industry,department,date}:{title:string;documentId:string;industry:string;department:string;date:string}){return <div className="flex min-w-0 flex-1 gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-lg border border-border bg-card text-emerald-400"><FileText className="size-4"/></span><div className="min-w-0"><h2 className="truncate text-sm font-medium">{title}</h2><p className="mt-1 flex flex-wrap gap-2 text-[11px] text-muted-foreground"><span className="font-mono">{documentId}</span><span>{industry}</span><span>{department}</span><span className="flex items-center gap-1"><Clock3 className="size-3"/>{new Date(date).toLocaleString()}</span></p></div></div>}
