"use client";
import { useEffect, useState } from "react";
import { Database, UploadCloud } from "lucide-react";
import { Button } from "@/components/ui/button";
import { createClient } from "@/lib/supabase/client";
import { clearMigratedLocalData, localWorkSummary, migrateLocalData, migrationComplete, setMigrationSkipped, type MigrationCounts } from "@/lib/cloud/migration-manager";

export function LocalMigration() {
  const [userId, setUserId] = useState(""); const [summary, setSummary] = useState({ sops: 0, versions: 0, documents: 0 }); const [visible, setVisible] = useState(false); const [busy, setBusy] = useState(false); const [progress, setProgress] = useState(0); const [result, setResult] = useState<MigrationCounts | null>(null); const [review, setReview] = useState(false);
  useEffect(() => { try { void createClient().auth.getUser().then(({ data }) => { if (!data.user) return; const found = localWorkSummary(); setUserId(data.user.id); setSummary(found); setVisible(!migrationComplete(data.user.id) && Object.values(found).some(Boolean)); }); } catch { /* auth configuration message appears elsewhere */ } }, []);
  if (!visible) return null;
  async function start() { setBusy(true); setResult(await migrateLocalData(userId, (done, count) => setProgress(count ? Math.round(done / count * 100) : 100))); setBusy(false); }
  return <section className="rounded-xl border border-emerald-400/20 bg-emerald-400/[0.05] p-5" aria-live="polite"><div className="flex items-start gap-3"><span className="grid size-10 place-items-center rounded-lg bg-emerald-400/10 text-emerald-300"><UploadCloud className="size-5" /></span><div className="flex-1"><h2 className="font-medium">Local work found</h2><p className="mt-1 text-sm text-muted-foreground">Import existing work into your account. Local copies remain until you explicitly clear them.</p>{review && <div className="mt-3 grid grid-cols-3 gap-2 text-center text-xs"><span className="rounded-lg bg-background/60 p-2">{summary.sops} SOPs</span><span className="rounded-lg bg-background/60 p-2">{summary.versions} versions</span><span className="rounded-lg bg-background/60 p-2">{summary.documents} sources</span></div>}{busy && <div className="mt-4"><div className="h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full bg-emerald-400 transition-all" style={{ width: `${progress}%` }} /></div><p className="mt-1 text-xs text-muted-foreground">Importing… {progress}%</p></div>}{result && <p className="mt-3 text-sm text-emerald-200">Imported {result.imported}, skipped {result.skipped}, failed {result.failed}.</p>}<div className="mt-4 flex flex-wrap gap-2"><Button onClick={() => void start()} disabled={busy}><Database /> Import to my account</Button><Button variant="outline" onClick={() => setReview(!review)} disabled={busy}>Review items</Button><Button variant="ghost" onClick={() => { setMigrationSkipped(userId); setVisible(false); }} disabled={busy}>Skip for now</Button>{result && result.failed === 0 && <Button variant="ghost" onClick={() => { if (confirm("Clear the migrated local copies from this browser?")) { clearMigratedLocalData(); setVisible(false); } }}>Clear migrated local data</Button>}</div></div></div></section>;
}
