"use client";
import { useEffect, useState } from "react";
import { CheckCircle2, CircleSlash2, Clock3, XCircle } from "lucide-react";
import { releaseFeatures } from "@/lib/release/features";

type Result = "not-checked" | "pass" | "fail" | "blocked";
type Check = { result: Result; notes: string; checkedAt: string | null };
const key = "processforge.release-check.v1";
const blank = (): Record<string, Check> => Object.fromEntries(releaseFeatures.map(feature => [feature.name, { result: "not-checked", notes: "", checkedAt: null }]));

export function ReleaseCheckDashboard() {
  const [checks, setChecks] = useState<Record<string, Check>>(blank);
  useEffect(() => { const timer = window.setTimeout(() => { try { const value = JSON.parse(localStorage.getItem(key) ?? "null") as unknown; if (value && typeof value === "object" && !Array.isArray(value)) setChecks(current => ({ ...current, ...(value as Record<string, Check>) })); } catch { localStorage.removeItem(key); } }, 0); return () => window.clearTimeout(timer); }, []);
  const update = (name: string, patch: Partial<Check>) => setChecks(current => { const next = { ...current, [name]: { ...current[name], ...patch, checkedAt: patch.result ? new Date().toISOString() : current[name]?.checkedAt ?? null } }; try { localStorage.setItem(key, JSON.stringify(next)); } catch { /* QA state is optional. */ } return next; });
  return <div className="space-y-4">{releaseFeatures.map(feature => { const check = checks[feature.name] ?? blank()[feature.name]; return <article key={feature.name} className="rounded-xl border border-border bg-card/40 p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-start"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-sm font-medium">{feature.name}</h2><span className="rounded-full border border-border px-2 py-0.5 text-[10px] uppercase text-muted-foreground">{feature.status}</span></div><p className="mt-2 text-xs leading-5 text-muted-foreground">{feature.steps}</p><p className="mt-2 text-[10px] text-muted-foreground">Last checked: {check.checkedAt ? new Date(check.checkedAt).toLocaleString() : "Never"}</p></div><fieldset className="flex flex-wrap gap-1" aria-label={`${feature.name} result`}>{(["pass","fail","blocked"] as Result[]).map(result => <button key={result} type="button" onClick={() => update(feature.name,{result})} aria-pressed={check.result===result} className="inline-flex items-center gap-1 rounded-md border border-border px-2.5 py-1.5 text-[11px] capitalize focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-400 data-[active=true]:border-emerald-500/50 data-[active=true]:bg-emerald-500/10" data-active={check.result===result}>{result==="pass"?<CheckCircle2 className="size-3"/>:result==="fail"?<XCircle className="size-3"/>:<CircleSlash2 className="size-3"/>}{result}</button>)}</fieldset></div><label className="mt-3 block text-[11px] text-muted-foreground">Notes<textarea value={check.notes} onChange={event=>update(feature.name,{notes:event.target.value})} className="mt-1.5 min-h-20 w-full rounded-md border border-input bg-background px-3 py-2 text-xs text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-400" maxLength={2000}/></label></article>})}<div className="flex items-center gap-2 text-xs text-muted-foreground"><Clock3 className="size-3"/>Results are stored only in this browser and never contain credentials.</div></div>;
}
