"use client";
import { useMemo, useState } from "react";
import { AlertTriangle, BarChart3, CheckCircle2, RefreshCw, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { analyzeSop } from "@/lib/analytics/sop-analytics";
import type { Sop } from "@/lib/sop-schema";
import type { AnalyticsScoreKey, SopAnalytics } from "@/types/sop-analytics";
import { getCloudLink } from "@/lib/cloud/sync-manager";
import { saveSopAnalytics } from "@/lib/cloud/sop-service";

const scoreLabels:Record<AnalyticsScoreKey,[string,string]>={completeness:["Completeness","Coverage of essential SOP sections."],clarity:["Clarity","Direct, specific and assignable language."],procedureStrength:["Procedure strength","Measurable sequence, ownership and evidence."],controlStrength:["Control strength","Approvals, escalation, checks and outcomes."],complianceReadiness:["Compliance readiness","Policy, audit and records guidance."],trainingReadiness:["Training readiness","Operator guidance and knowledge validation."],knowledgeGrounding:["Knowledge grounding","Support from selected company references."]};

export function SopAnalyticsCard({sop,onAnalytics,onSave}:{sop:Sop;onAnalytics?:(analytics:SopAnalytics)=>void;onSave?:(analytics:SopAnalytics)=>Promise<boolean>}){
  const [analyzedAt,setAnalyzedAt]=useState(()=>new Date().toISOString());const [saving,setSaving]=useState(false);const [saveError,setSaveError]=useState(false);
  const analytics=useMemo(()=>analyzeSop(sop,analyzedAt),[sop,analyzedAt]);
  const reanalyze=async()=>{const next=analyzeSop(sop);setAnalyzedAt(next.analyzedAt);onAnalytics?.(next);const link=getCloudLink(sop.documentId);const save=onSave??(link?async(value:SopAnalytics)=>(await saveSopAnalytics(link.cloudId,value)).ok:undefined);if(save){setSaving(true);setSaveError(!(await save(next)));setSaving(false)}};
  const prompt=(text:string)=>window.dispatchEvent(new CustomEvent("processforge:editor-prompt",{detail:text}));
  return <section className="border-t border-border/80 p-4 sm:p-5" aria-labelledby="sop-analytics-heading"><div className="rounded-xl border border-border bg-background/70 p-4 sm:p-5">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><BarChart3 className="size-4 text-emerald-400"/><h2 id="sop-analytics-heading" className="text-sm font-medium">SOP Analytics</h2></div><p className="mt-1 text-[11px] text-muted-foreground">Deterministic quality and operational-risk analysis.</p></div><Button variant="outline" size="sm" onClick={()=>void reanalyze()} disabled={saving}><RefreshCw className={saving?"animate-spin":""}/>{saving?"Saving…":"Reanalyze"}</Button></div>
    <div className="mt-4 grid gap-3 md:grid-cols-[10rem_1fr]"><div className="rounded-xl border border-border bg-card/60 p-4 text-center"><p className="text-4xl font-semibold text-emerald-400">{analytics.overallQuality}</p><p className="mt-1 text-xs text-muted-foreground">Overall quality</p><span className={`mt-3 inline-flex rounded-full px-2 py-1 text-[10px] font-medium ${analytics.riskLevel==="high"||analytics.riskLevel==="critical"?"bg-rose-500/10 text-rose-300":"bg-amber-500/10 text-amber-200"}`}>{analytics.riskLevel.toUpperCase()} RISK</span></div><div className="grid gap-2 sm:grid-cols-2">{Object.entries(analytics.scores).map(([key,value])=>{const [label,description]=scoreLabels[key as AnalyticsScoreKey];return <div key={key} className="rounded-lg border border-border/70 p-3" title={description}><div className="flex justify-between text-[11px]"><span>{label}</span><span className="font-mono text-muted-foreground">{value}%</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-secondary"><div className="h-full rounded-full bg-emerald-500" style={{width:`${value}%`}}/></div><p className="mt-1.5 text-[10px] text-muted-foreground">{description}</p></div>})}</div></div>
    <div className="mt-4 flex flex-wrap gap-1.5">{analytics.badges.map(badge=><span key={badge} className="inline-flex items-center gap-1 rounded-full border border-emerald-500/20 bg-emerald-500/10 px-2 py-1 text-[10px] text-emerald-300">{badge==="AI Enhanced"?<Sparkles className="size-3"/>:<CheckCircle2 className="size-3"/>}{badge}</span>)}</div>
    <div className="mt-5"><h3 className="text-xs font-medium">Top findings</h3>{analytics.findings.length===0?<p className="mt-2 text-xs text-emerald-300">No material deterministic risks detected.</p>:<div className="mt-2 space-y-2">{analytics.findings.slice(0,5).map(f=><article key={f.id} className="rounded-lg border border-border/70 p-3"><div className="flex items-start gap-2"><AlertTriangle className="mt-0.5 size-3.5 shrink-0 text-amber-400"/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="text-xs font-medium">{f.title}</p><span className="text-[9px] uppercase tracking-wider text-muted-foreground">{f.severity}</span></div><p className="mt-1 text-[11px] leading-4 text-muted-foreground">{f.description} {f.recommendation}</p><Button variant="link" size="xs" className="mt-1 h-auto p-0 text-emerald-400" onClick={()=>prompt(f.suggestedEditorAction)}>Use in AI Editor</Button></div></div></article>)}</div>}</div>
    <div className="mt-4 flex flex-wrap justify-between gap-2 text-[10px] text-muted-foreground"><span>Last analyzed {new Date(analytics.analyzedAt).toLocaleString()}</span>{saveError&&<span role="alert" className="text-amber-300">Cloud analytics save failed. Reanalyze to retry.</span>}</div>
  </div></section>
}
