"use client";
import { useCallback,useEffect,useState } from "react";import Link from "next/link";import { useRouter } from "next/navigation";import { Copy,Heart,Share2,Sparkles,Star } from "lucide-react";
import { WorkspaceHeader } from "@/components/processforge/workspace-header";import { Button } from "@/components/ui/button";import { fetchMarketplaceTemplate,copyTemplateToWorkspace,rateTemplate,toggleTemplateFavorite,trackTemplateView } from "@/lib/marketplace/template-service";import { fetchWorkspaces,type Workspace } from "@/lib/cloud/workspace-service";import { queueComplianceAiFix } from "@/lib/compliance/ai-fix";import { analyzeSop } from "@/lib/analytics/sop-analytics";import { analyzeCompliance } from "@/lib/compliance/compliance-engine";import type { MarketplaceTemplate } from "@/types/marketplace";

export function TemplateDetail({slug}:{slug:string}){
 const router=useRouter(),[item,setItem]=useState<MarketplaceTemplate|null>(null),[spaces,setSpaces]=useState<Workspace[]>([]),[workspace,setWorkspace]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[favorite,setFavorite]=useState(false);
 const load=useCallback(async()=>{const[result,workspaces]=await Promise.all([fetchMarketplaceTemplate(slug),fetchWorkspaces()]);if(result.ok){setItem(result.data);void trackTemplateView(result.data.id)}else setError(result.error.message);if(workspaces.ok){setSpaces(workspaces.data);setWorkspace(workspaces.data[0]?.id??"")}},[slug]);
 useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);
 if(!item)return <main className="min-h-screen bg-background"><WorkspaceHeader/><div className="mx-auto max-w-5xl p-12 text-center text-sm text-muted-foreground">{error||"Loading template…"}</div></main>;
 const analytics=analyzeSop(item.sop),compliance=analyzeCompliance(item.sop);
 const use=async(customize=false)=>{if(!workspace){router.push(`/login?returnTo=${encodeURIComponent(`/marketplace/${slug}`)}`);return}setBusy(true);const result=await copyTemplateToWorkspace(item,workspace);setBusy(false);if(!result.ok){setError(result.error.message);return}if(customize)queueComplianceAiFix("Customize this template for my company, industry, team, and operational requirements. Preserve its intent, clearly mark assumptions, and do not invent company policy.");router.push(`/create?cloud=${result.data}`)};
 const share=async()=>{if(navigator.share)await navigator.share({title:item.title,url:location.href});else await navigator.clipboard.writeText(location.href)};
 return <main className="min-h-screen bg-background"><WorkspaceHeader/><div className="mx-auto max-w-6xl px-4 py-8 sm:px-6"><div className="grid gap-6 lg:grid-cols-[1fr_20rem]"><article className="rounded-2xl border border-border bg-card/35 p-5 sm:p-8"><div className="flex flex-wrap gap-2">{item.tags.map(x=><span key={x} className="rounded-full bg-secondary px-2 py-1 text-[10px]">{x}</span>)}</div><h1 className="mt-4 text-3xl font-semibold">{item.title}</h1><p className="mt-3 text-sm leading-6 text-muted-foreground">{item.description}</p><div className="mt-5 grid gap-3 text-xs sm:grid-cols-4"><Meta label="Industry" value={item.industry||"General"}/><Meta label="Department" value={item.department||"Cross-functional"}/><Meta label="Category" value={item.categoryName}/><Meta label="Version" value={item.version}/></div><section className="mt-8"><h2 className="text-sm font-medium">SOP preview</h2><div className="mt-3 whitespace-pre-wrap rounded-xl border border-border bg-background/70 p-5 text-xs leading-6 text-muted-foreground">{item.previewContent}</div></section><section className="mt-8 grid gap-3 sm:grid-cols-2"><Summary title="Analytics summary" values={[["Overall quality",analytics.overallQuality],["Procedure strength",analytics.scores.procedureStrength],["Control strength",analytics.scores.controlStrength]]}/><Summary title="Compliance summary" values={[["Compliance",compliance.complianceScore],["Audit readiness",compliance.auditReadiness],["Governance",compliance.governanceScore]]}/></section></article>
 <aside className="h-fit space-y-4 rounded-2xl border border-border bg-card/50 p-5"><div><p className="text-xs text-muted-foreground">Created by</p><Link href={`/creators/${item.creatorId}`} className="mt-1 block text-sm font-medium text-emerald-400">{item.creatorName}</Link></div><div className="grid grid-cols-2 gap-2 text-xs"><Meta label="Rating" value={`${item.ratingAverage.toFixed(1)} (${item.ratingCount})`}/><Meta label="Uses" value={String(item.usageCount)}/><Meta label="Updated" value={new Date(item.updatedAt).toLocaleDateString()}/><Meta label="Risk" value={item.riskLevel||compliance.riskRating}/></div><label className="block text-[11px] text-muted-foreground">Copy to workspace<select className="mt-1.5 h-9 w-full rounded-md border border-input bg-background px-2 text-xs" value={workspace} onChange={e=>setWorkspace(e.target.value)}><option value="">Sign in to choose</option>{spaces.filter(x=>x.role!=="viewer").map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><Button className="w-full" disabled={busy} onClick={()=>void use(false)}><Copy/>{busy?"Copying…":"Use Template"}</Button><Button className="w-full" variant="outline" disabled={busy} onClick={()=>void use(true)}><Sparkles/>Customize with AI</Button><div className="flex gap-2"><Button variant="outline" className="flex-1" onClick={()=>void toggleTemplateFavorite(item.id,!favorite).then(r=>{if(r.ok)setFavorite(!favorite)})}><Heart className={favorite?"fill-current text-rose-400":""}/>{favorite?"Saved":"Favorite"}</Button><Button variant="outline" size="icon" aria-label="Share template" onClick={()=>void share()}><Share2/></Button></div><div><p className="mb-2 text-[11px] text-muted-foreground">Rate this template</p><div className="flex gap-1">{[1,2,3,4,5].map(x=><Button key={x} variant="ghost" size="icon-sm" aria-label={`Rate ${x} stars`} onClick={()=>void rateTemplate(item.id,x).then(r=>{if(!r.ok)setError(r.error.message)})}><Star className="text-amber-300"/></Button>)}</div></div>{error&&<p role="alert" className="text-xs text-amber-300">{error}</p>}</aside></div></div></main>
}
function Meta({label,value}:{label:string;value:string}){return <div><p className="text-[10px] uppercase tracking-wider text-muted-foreground">{label}</p><p className="mt-1 font-medium">{value}</p></div>}
function Summary({title,values}:{title:string;values:Array<[string,number]>}){return <div className="rounded-xl border border-border p-4"><h3 className="text-xs font-medium">{title}</h3><div className="mt-3 space-y-2">{values.map(([label,value])=><div key={label} className="flex justify-between text-xs"><span className="text-muted-foreground">{label}</span><span className="text-emerald-400">{value}%</span></div>)}</div></div>}
