"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { GitCompareArrows, History, Pencil, RotateCcw, Trash2 } from "lucide-react";
import { Button, buttonVariants } from "@/components/ui/button";
import { VersionCompare } from "@/components/processforge/version-compare";
import { deleteSopVersion, getSopVersions, renameSopVersion, type SopVersion } from "@/lib/version-manager";
import { deleteVersion as deleteCloudVersion, fetchVersions, renameVersion as renameCloudVersion } from "@/lib/cloud/version-service";

export function VersionHistory(){const [versions,setVersions]=useState<SopVersion[]>([]);const [cloudMode,setCloudMode]=useState(false);const [leftId,setLeftId]=useState("");const [rightId,setRightId]=useState("");
 useEffect(()=>{let active=true;void fetchVersions().then(result=>{if(!active)return;if(result.ok&&result.data.length){setCloudMode(true);setVersions(result.data.map(v=>({id:v.id,documentId:v.sop.documentId,versionNumber:Math.max(1,Number.parseInt(v.versionNumber,10)||1),name:`Version ${v.versionNumber}`,timestamp:v.timestamp,changeSummary:v.changeSummary,sop:v.sop})))}else setVersions(getSopVersions())});return()=>{active=false}},[]);
 const left=useMemo(()=>versions.find(v=>v.id===leftId),[versions,leftId]);const right=useMemo(()=>versions.find(v=>v.id===rightId),[versions,rightId]);
 const rename=(version:SopVersion)=>{const name=prompt("Rename this version",version.name);if(!name)return;if(cloudMode)void renameCloudVersion(version.id,name).then(r=>{if(r.ok)setVersions(current=>current.map(v=>v.id===version.id?{...v,name,changeSummary:name}:v))});else setVersions(renameSopVersion(version.id,name))};
 const remove=(id:string)=>{if(!confirm("Delete this version snapshot?"))return;if(cloudMode)void deleteCloudVersion(id).then(r=>{if(r.ok)setVersions(current=>current.filter(v=>v.id!==id))});else setVersions(deleteSopVersion(id))};
 if(!versions.length)return <div className="py-24 text-center"><History className="mx-auto size-8 text-muted-foreground"/><h2 className="mt-4 font-medium">No versions saved yet</h2><Link href="/create" className={buttonVariants({className:"mt-5"})}>Create an SOP</Link></div>;
 return <><div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_19rem]"><div className="divide-y divide-border rounded-xl border border-border bg-card/30 px-4">{versions.map(v=><article key={v.id} className="flex flex-col gap-4 py-5 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><div className="flex gap-2"><h2 className="truncate text-sm font-medium">{v.name}</h2><span className="rounded-full bg-secondary px-2 py-0.5 text-[9px]">v{v.versionNumber}</span></div><p className="mt-1 text-[11px] text-muted-foreground">{v.changeSummary}</p><p className="mt-1 font-mono text-[10px] text-muted-foreground">{v.documentId} · {new Date(v.timestamp).toLocaleString()}</p></div><div className="flex gap-1"><Link href={`/create?${cloudMode?"cloudVersion":"version"}=${encodeURIComponent(v.id)}`} className={buttonVariants({variant:"outline",size:"sm"})}><RotateCcw/>Restore</Link><Button variant="ghost" size="icon-sm" onClick={()=>rename(v)} aria-label="Rename version"><Pencil/></Button><Button variant="ghost" size="icon-sm" onClick={()=>remove(v.id)} aria-label="Delete version"><Trash2/></Button></div></article>)}</div><aside className="h-fit rounded-xl border border-border bg-card/40 p-4"><h2 className="flex items-center gap-2 text-sm font-medium"><GitCompareArrows className="size-4 text-emerald-400"/>Compare versions</h2><VersionSelect label="Earlier version" value={leftId} setValue={setLeftId} versions={versions}/><VersionSelect label="Later version" value={rightId} setValue={setRightId} versions={versions}/></aside></div>{left&&right&&left.id!==right.id&&<VersionCompare before={left} after={right}/>}</>
}
function VersionSelect({label,value,setValue,versions}:{label:string;value:string;setValue:(v:string)=>void;versions:SopVersion[]}){return <label className="mt-4 block text-[11px] text-muted-foreground">{label}<select value={value} onChange={e=>setValue(e.target.value)} className="mt-1.5 h-9 w-full rounded-lg border border-border bg-background px-2 text-xs"><option value="">Select version</option>{versions.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label>}
