import { z } from "zod";
import { authenticatedClient } from "@/lib/cloud/auth";
import { cloudFailure, type CloudResult } from "@/lib/cloud/result";
import type { Json } from "@/types/json";
export type SopComment={id:string;sopId:string;workspaceId:string;authorId:string;section:string;message:string;createdAt:string;updatedAt:string};
export type SopActivity={id:string;workspaceId:string;sopId:string|null;actorId:string|null;type:string;summary:string;metadata:Json;createdAt:string};
const messageSchema=z.string().trim().min(1).max(2000);const sectionSchema=z.string().trim().min(1).max(80);
export async function fetchComments(sopId:string):Promise<CloudResult<SopComment[]>>{const auth=await authenticatedClient();if(!auth.ok)return auth;const{data,error}=await auth.data.client.from("sop_comments").select("*").eq("sop_id",sopId).order("created_at",{ascending:false});return error?cloudFailure("Could not load comments."):{ok:true,data:(data??[]).map(row=>({id:row.id,sopId:row.sop_id,workspaceId:row.workspace_id,authorId:row.author_id,section:row.section,message:row.message,createdAt:row.created_at,updatedAt:row.updated_at}))}}
export async function addComment(sopId:string,workspaceId:string,section:string,message:string):Promise<CloudResult<SopComment>>{const text=messageSchema.safeParse(message),area=sectionSchema.safeParse(section);if(!text.success||!area.success)return cloudFailure("Enter a valid comment and section.","validation");const auth=await authenticatedClient();if(!auth.ok)return auth;const{data,error}=await auth.data.client.from("sop_comments").insert({sop_id:sopId,workspace_id:workspaceId,author_id:auth.data.userId,section:area.data,message:text.data}).select().single();if(error||!data)return cloudFailure("Could not add the comment.");await addActivity(workspaceId,sopId,"comment_added",`Comment added to ${area.data}`);return{ok:true,data:{id:data.id,sopId:data.sop_id,workspaceId:data.workspace_id,authorId:data.author_id,section:data.section,message:data.message,createdAt:data.created_at,updatedAt:data.updated_at}}}
export async function editComment(id:string,message:string):Promise<CloudResult<true>>{const parsed=messageSchema.safeParse(message);if(!parsed.success)return cloudFailure("Enter a valid comment.","validation");const auth=await authenticatedClient();if(!auth.ok)return auth;const{error}=await auth.data.client.from("sop_comments").update({message:parsed.data}).eq("id",id);return error?cloudFailure("You can only edit your own comments."):{ok:true,data:true}}
export async function deleteComment(id:string):Promise<CloudResult<true>>{const auth=await authenticatedClient();if(!auth.ok)return auth;const{error}=await auth.data.client.from("sop_comments").delete().eq("id",id);return error?cloudFailure("You cannot delete this comment."):{ok:true,data:true}}
export async function fetchActivity(workspaceId?:string):Promise<CloudResult<SopActivity[]>>{const auth=await authenticatedClient();if(!auth.ok)return auth;let query=auth.data.client.from("sop_activity").select("*").order("created_at",{ascending:false}).limit(50);if(workspaceId)query=query.eq("workspace_id",workspaceId);const{data,error}=await query;return error?cloudFailure("Could not load activity."):{ok:true,data:(data??[]).map(row=>({id:row.id,workspaceId:row.workspace_id,sopId:row.sop_id,actorId:row.actor_id,type:row.activity_type,summary:row.summary,metadata:row.metadata,createdAt:row.created_at}))}}
export async function addActivity(workspaceId:string,sopId:string|null,type:string,summary:string,metadata:Json={}):Promise<CloudResult<true>>{const auth=await authenticatedClient();if(!auth.ok)return auth;const{error}=await auth.data.client.from("sop_activity").insert({workspace_id:workspaceId,sop_id:sopId,actor_id:auth.data.userId,activity_type:type,summary:summary.slice(0,500),metadata});return error?cloudFailure("Activity could not be recorded."):{ok:true,data:true}}
export async function updateWorkflowStatus(sopId:string,status:"draft"|"in_review"|"approved"|"archived"):Promise<CloudResult<true>>{const auth=await authenticatedClient();if(!auth.ok)return auth;const current=await auth.data.client.from("sops").select("workspace_id,status").eq("id",sopId).single();if(current.error||!current.data)return cloudFailure("SOP could not be found.");const role=await auth.data.client.rpc("workspace_role_for",{target:current.data.workspace_id});if(role.error||!role.data)return cloudFailure("Workspace permission could not be verified.");if(status==="approved"&&!(["owner","admin"] as string[]).includes(role.data))return cloudFailure("Only owners and admins can approve SOPs.","auth");if(status==="in_review"&&role.data==="viewer")return cloudFailure("Viewers cannot request a review.","auth");const{error}=await auth.data.client.from("sops").update({status,is_archived:status==="archived"}).eq("id",sopId);if(error)return cloudFailure("Workflow status could not be updated.");await addActivity(current.data.workspace_id,sopId,status==="approved"?"approval_granted":"review_requested",status==="approved"?"Approval granted":"Review requested");return{ok:true,data:true}}
