import { z } from "zod";
import { authenticatedClient } from "@/lib/cloud/auth";
import { cloudFailure, type CloudResult } from "@/lib/cloud/result";
export type WorkspaceRole="owner"|"admin"|"editor"|"viewer";
export type Workspace={id:string;name:string;ownerId:string;isPersonal:boolean;role:WorkspaceRole;createdAt:string};
export type WorkspaceMember={userId:string;role:WorkspaceRole;joinedAt:string;displayName:string};
export type WorkspaceInvitation={id:string;workspaceId:string;email:string;role:WorkspaceRole;status:string;createdAt:string;expiresAt:string;sentAt:string|null;emailDeliveryStatus:"not_sent"|"pending"|"sent"|"failed";emailDeliveryError:string|null};
const ACTIVE_KEY="processforge.active-workspace.v1";const nameSchema=z.string().trim().min(1).max(100);
export const inviteEmailSchema=z.string().transform(normalizeInviteEmail).pipe(z.email("Enter a valid email address.").max(320));
export function normalizeInviteEmail(value:string){return value.normalize("NFKC").replace(/[\u200B-\u200D\uFEFF]/g,"").trim().toLowerCase()}
export function getActiveWorkspaceId(){if(typeof window==="undefined")return null;try{return localStorage.getItem(ACTIVE_KEY)}catch{return null}}
export function setActiveWorkspaceId(id:string){try{localStorage.setItem(ACTIVE_KEY,id);window.dispatchEvent(new CustomEvent("processforge:workspace-changed",{detail:id}))}catch{/* selection remains in component state */}}
export async function fetchWorkspaces():Promise<CloudResult<Workspace[]>>{const auth=await authenticatedClient();if(!auth.ok)return auth;const{data:members,error}=await auth.data.client.from("workspace_members").select("*").eq("user_id",auth.data.userId);if(error)return cloudFailure("Could not load workspaces.");const ids=(members??[]).map(m=>m.workspace_id);if(!ids.length)return{ok:true,data:[]};const{data,error:workspaceError}=await auth.data.client.from("workspaces").select("*").in("id",ids).order("created_at");if(workspaceError)return cloudFailure("Could not load workspaces.");return{ok:true,data:(data??[]).map(row=>({id:row.id,name:row.name,ownerId:row.owner_id,isPersonal:row.is_personal,createdAt:row.created_at,role:members?.find(m=>m.workspace_id===row.id)?.role??"viewer"}))}}
export async function activeWorkspace():Promise<CloudResult<Workspace>>{const list=await fetchWorkspaces();if(!list.ok)return list;const selected=getActiveWorkspaceId();const workspace=list.data.find(item=>item.id===selected)??list.data[0];if(!workspace)return cloudFailure("No workspace is available.");if(selected!==workspace.id)setActiveWorkspaceId(workspace.id);return{ok:true,data:workspace}}
export async function createWorkspace(name:string):Promise<CloudResult<string>>{const parsed=nameSchema.safeParse(name);if(!parsed.success)return cloudFailure("Enter a workspace name.","validation");const auth=await authenticatedClient();if(!auth.ok)return auth;const{data,error}=await auth.data.client.rpc("create_workspace",{workspace_name:parsed.data});if(error||!data)return cloudFailure("Could not create the workspace.");setActiveWorkspaceId(data);return{ok:true,data}}
export async function renameWorkspace(id:string,name:string):Promise<CloudResult<true>>{const parsed=nameSchema.safeParse(name);if(!parsed.success)return cloudFailure("Enter a valid workspace name.","validation");const auth=await authenticatedClient();if(!auth.ok)return auth;const{error}=await auth.data.client.from("workspaces").update({name:parsed.data}).eq("id",id);return error?cloudFailure("You do not have permission to rename this workspace."):{ok:true,data:true}}
export async function deleteWorkspace(id:string):Promise<CloudResult<true>>{const auth=await authenticatedClient();if(!auth.ok)return auth;const{error}=await auth.data.client.from("workspaces").delete().eq("id",id);return error?cloudFailure("Only the owner can delete this workspace."):{ok:true,data:true}}
export async function fetchMembers(workspaceId:string):Promise<CloudResult<WorkspaceMember[]>>{const auth=await authenticatedClient();if(!auth.ok)return auth;const{data,error}=await auth.data.client.from("workspace_members").select("*").eq("workspace_id",workspaceId);if(error)return cloudFailure("Could not load team members.");const ids=(data??[]).map(row=>row.user_id);const profiles=ids.length?await auth.data.client.from("profiles").select("id,display_name").in("id",ids):{data:[]};return{ok:true,data:(data??[]).map(row=>({userId:row.user_id,role:row.role,joinedAt:row.joined_at,displayName:row.user_id===auth.data.userId?"You":profiles.data?.find(profile=>profile.id===row.user_id)?.display_name||`Member ${row.user_id.slice(0,8)}`}))}}
export async function inviteMember(workspaceId:string,email:string,role:Exclude<WorkspaceRole,"owner">):Promise<CloudResult<true>>{
  const parsed=inviteEmailSchema.safeParse(email);if(!parsed.success)return cloudFailure("Enter a valid email address.","validation");
  const auth=await authenticatedClient();if(!auth.ok)return auth;
  const currentEmail=normalizeInviteEmail((await auth.data.client.auth.getUser()).data.user?.email??"");
  if(parsed.data===currentEmail)return cloudFailure("You cannot invite yourself.","validation");
  try{const response=await fetch("/api/invitations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"create",workspaceId,email:parsed.data,role})});const payload:unknown=await response.json().catch(()=>null);if(response.ok)return{ok:true,data:true};if(typeof payload==="object"&&payload!==null&&"invitationCreated" in payload&&payload.invitationCreated===true)return cloudFailure("Invitation created but email delivery failed.","provider");const message=typeof payload==="object"&&payload!==null&&"error" in payload&&typeof payload.error==="string"?payload.error:"Could not send the invitation.";return cloudFailure(message,response.status===403?"auth":"provider")}catch{return cloudFailure("Email delivery is unavailable. Please retry.","offline")}
}
export async function fetchInvitations(workspaceId?:string):Promise<CloudResult<WorkspaceInvitation[]>>{const auth=await authenticatedClient();if(!auth.ok)return auth;let query=auth.data.client.from("workspace_invitations").select("*").eq("status","pending").order("created_at",{ascending:false});if(workspaceId)query=query.eq("workspace_id",workspaceId);const{data,error}=await query;return error?cloudFailure("Could not load invitations."):{ok:true,data:(data??[]).map(row=>({id:row.id,workspaceId:row.workspace_id,email:row.email,role:row.role,status:row.status,createdAt:row.created_at,expiresAt:row.expires_at,sentAt:row.sent_at,emailDeliveryStatus:row.email_delivery_status,emailDeliveryError:row.email_delivery_error}))}}
export async function resendInvitation(invitationId:string):Promise<CloudResult<true>>{return invitationAction("resend",invitationId)}
export async function revokeInvitation(invitationId:string):Promise<CloudResult<true>>{return invitationAction("revoke",invitationId)}
async function invitationAction(action:"resend"|"revoke",invitationId:string):Promise<CloudResult<true>>{try{const response=await fetch("/api/invitations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,invitationId})});const payload:unknown=await response.json().catch(()=>null);if(response.ok)return{ok:true,data:true};return cloudFailure(typeof payload==="object"&&payload!==null&&"error" in payload&&typeof payload.error==="string"?payload.error:"Invitation action failed.",response.status===429?"provider":"validation")}catch{return cloudFailure("Invitation service is unavailable.","offline")}}
export async function acceptInvitation(id:string):Promise<CloudResult<string>>{const auth=await authenticatedClient();if(!auth.ok)return auth;const{data,error}=await auth.data.client.rpc("accept_workspace_invitation",{invitation_id:id});if(error||!data)return cloudFailure("The invitation is invalid or expired.");setActiveWorkspaceId(data);return{ok:true,data}}
export async function removeMember(workspaceId:string,userId:string):Promise<CloudResult<true>>{const auth=await authenticatedClient();if(!auth.ok)return auth;const{error}=await auth.data.client.from("workspace_members").delete().eq("workspace_id",workspaceId).eq("user_id",userId);return error?cloudFailure("You do not have permission to remove this member."):{ok:true,data:true}}
export async function updateMemberRole(workspaceId:string,userId:string,role:Exclude<WorkspaceRole,"owner">):Promise<CloudResult<true>>{const auth=await authenticatedClient();if(!auth.ok)return auth;const{error}=await auth.data.client.from("workspace_members").update({role}).eq("workspace_id",workspaceId).eq("user_id",userId);return error?cloudFailure("You do not have permission to change this role."):{ok:true,data:true}}
