import { z } from "zod";
import { authenticatedClient } from "@/lib/cloud/auth";
import { cloudFailure, type CloudResult } from "@/lib/cloud/result";

export type WorkspaceRole="owner"|"admin"|"editor"|"viewer";
export type Workspace={id:string;name:string;ownerId:string;isPersonal:boolean;role:WorkspaceRole;createdAt:string};
const ACTIVE_KEY="processforge.active-workspace.v1";
const nameSchema=z.string().trim().min(1).max(100);

export function getActiveWorkspaceId(){if(typeof window==="undefined")return null;try{return localStorage.getItem(ACTIVE_KEY)}catch{return null}}
export function setActiveWorkspaceId(id:string){try{localStorage.setItem(ACTIVE_KEY,id);window.dispatchEvent(new CustomEvent("processforge:workspace-changed",{detail:id}))}catch{/* selection remains in component state */}}
export async function fetchWorkspaces():Promise<CloudResult<Workspace[]>>{const auth=await authenticatedClient();if(!auth.ok)return auth;const{data:members,error}=await auth.data.client.from("workspace_members").select("*").eq("user_id",auth.data.userId);if(error)return cloudFailure("Could not load workspaces.");const ids=(members??[]).map(member=>member.workspace_id);if(!ids.length)return{ok:true,data:[]};const{data,error:workspaceError}=await auth.data.client.from("workspaces").select("*").in("id",ids).order("created_at");if(workspaceError)return cloudFailure("Could not load workspaces.");return{ok:true,data:(data??[]).map(row=>({id:row.id,name:row.name,ownerId:row.owner_id,isPersonal:row.is_personal,createdAt:row.created_at,role:members?.find(member=>member.workspace_id===row.id)?.role??"viewer"}))}}
export async function activeWorkspace():Promise<CloudResult<Workspace>>{const list=await fetchWorkspaces();if(!list.ok)return list;const selected=getActiveWorkspaceId();const workspace=list.data.find(item=>item.id===selected)??list.data[0];if(!workspace)return cloudFailure("No workspace is available.");if(selected!==workspace.id)setActiveWorkspaceId(workspace.id);return{ok:true,data:workspace}}
export async function createWorkspace(name:string):Promise<CloudResult<string>>{const parsed=nameSchema.safeParse(name);if(!parsed.success)return cloudFailure("Enter a workspace name.","validation");const auth=await authenticatedClient();if(!auth.ok)return auth;const{data,error}=await auth.data.client.rpc("create_workspace",{workspace_name:parsed.data});if(error||!data)return cloudFailure("Could not create the workspace.");setActiveWorkspaceId(data);return{ok:true,data}}
export async function renameWorkspace(id:string,name:string):Promise<CloudResult<true>>{const parsed=nameSchema.safeParse(name);if(!parsed.success)return cloudFailure("Enter a valid workspace name.","validation");const auth=await authenticatedClient();if(!auth.ok)return auth;const{data,error}=await auth.data.client.from("workspaces").update({name:parsed.data}).eq("id",id).eq("owner_id",auth.data.userId).select("id").maybeSingle();return error||!data?cloudFailure("Only the workspace owner can rename this workspace."):{ok:true,data:true}}
export async function deleteWorkspace(id:string):Promise<CloudResult<true>>{const auth=await authenticatedClient();if(!auth.ok)return auth;const{data,error}=await auth.data.client.from("workspaces").delete().eq("id",id).eq("owner_id",auth.data.userId).eq("is_personal",false).select("id").maybeSingle();return error||!data?cloudFailure("Only the owner can delete a non-personal workspace."):{ok:true,data:true}}
